Proyecto_CineALL/Proyecto_CineALL/Controllers/PeliculasController.cs
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto_CineALL.ServiceReference1;

namespace Proyecto_CineALL.Controllers
{
    public class PeliculasController : Controller
    {
        Service1Client servicio = new Service1Client();
        public ActionResult Pelicula()
        {
            return View(servicio.listPeliculas());
        }

        public ActionResult Create()
        {
            ViewBag.tipoPelicula = new SelectList(servicio.listTipoPelicula(), "codigo", "descripcion");
            return View(new Peliculas());
        }
        [HttpPost]
        public ActionResult Create(Peliculas reg, HttpPostedFileBase archivo2)
        {
            if (archivo2 == null || archivo2.ContentLength <= 0)
            {
                ViewBag.mensaje = "Seleccione una imagen";
                ViewBag.tipoPelicula = new SelectList(servicio.listTipoPelicula(), "codigo", "descripcion");

                return View(reg);
            }
            //si seleccionaste, lo guardamos en la carpeta FOTOS
            string ruta = "~/FOTOS/" + System.IO.Path.GetFileName(archivo2.FileName);
            reg.rutaimg = ruta;
            archivo2.SaveAs(Server.MapPath(ruta));

            ViewBag.tipoPelicula = new SelectList(servicio.listTipoPelicula(), "codigo", "descripcion");
            ViewBag.mensaje = servicio.addPelicula(reg);
            return View(reg);
        }


        public ActionResult Edit(string codigo)
        {
            if (string.IsNullOrEmpty(codigo)) return RedirectToAction("Pelicula");
            Peliculas reg = servicio.listPeliculas().Where(x => x.codigo == codigo).FirstOrDefault();
            ViewBag.tipoPelicula = new SelectList(servicio.listTipoPelicula(), "codigo", "descripcion");
            return View(reg);
        }
        [HttpPost]
        public ActionResult Edit(Peliculas reg, HttpPostedFileBase archivo2)
        {
            if (archivo2 != null)
            {
                //si seleccionaste, lo guardamos en la carpeta FOTOS
                string ruta = "~/FOTOS/" + System.IO.Path.GetFileName(archivo2.FileName);
                archivo2.SaveAs(Server.MapPath(ruta));
                reg.rutaimg = ruta;
            }

            ViewBag.mensaje = servicio.updatePelicula(reg);
            ViewBag.tipoPelicula = new SelectList(servicio.listTipoPelicula(), "codigo", "descripcion");
            return View(reg);
        }


        public ActionResult Delete(Peliculas reg)
        {
            TempData["mensaje"] = servicio.deletePelicula(reg);
            return RedirectToAction("Pelicula");
        }
    }
}

Proyecto_CineALL/Proyecto_CineALL/Views/Peliculas/Create.cshtml
@model Models.Peliculas
@using Models
@{
    ViewBag.Title = "Create";
}
<style>


    body {
        background-image: url('/FOTOS/BLACK2.PNG');
        background-repeat: no-repeat;
        background-size: cover;
    }
</style>
<body>
    <br />
    <h2>Crear</h2>
    @{
        var listado = new List<SelectListItem>() {
         new SelectListItem()
          {
              Text = "Activo",
              Value = "A"

          },
        new SelectListItem()
        {
            Text="Inhabilitado",
            Value="I"

        }
    };
    }

    @using (Html.BeginForm("Create", "Peliculas", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Peliculas</h4>
    <br />
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.idTipo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("idTipo", ViewBag.tipoPelicula as SelectList)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.fechaEstreno, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.fechaEstreno, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.fechaEstreno, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.fechaFinal, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.fechaFinal, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.fechaFinal, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.entradas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.entradas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.entradas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.entradasRestantes, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.entradasRestantes, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.entradasRestantes, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("estado", listado)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.rutaimg, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBox("archivo2", "", new { type = "file", accept = "image/*" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-success" /> |
            @Html.ActionLink("Retornar", "Pelicula", null, new { @class = "btn btn-info" })
        </div>
    </div>
</div>
    }
    <div>
        @ViewBag.mensaje
    </div>
</body>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Proyecto_CineALL/Proyecto_CineALL/Views/Peliculas/Edit.cshtml
@model Models.Peliculas
@using Models
@{
    ViewBag.Title = "Edit";
}
<style>


    body {
        background-image: url('/FOTOS/BLACK3.PNG');
        background-repeat: no-repeat;
        background-size: cover;
    }
</style>
<body>
    <br />
    <h2>Actualizar</h2>
    @{
        var listado = new List<SelectListItem>() {
         new SelectListItem()
          {
              Text = "Activo",
              Value = "A"

          },
        new SelectListItem()
        {
            Text="Inhabilitado",
            Value="I"

        }
    };
    }

    @using (Html.BeginForm("Edit", "Peliculas", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Peliculas</h4>
            <br />
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.codigo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.codigo, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                    @Html.ValidationMessageFor(model => model.codigo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.idTipo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("idTipo", ViewBag.tipoPelicula as SelectList)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.fechaEstreno, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fechaEstreno, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.fechaEstreno, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.fechaFinal, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fechaFinal, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.fechaFinal, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.entradas, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.entradas, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.entradas, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.entradasRestantes, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.entradasRestantes, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.entradasRestantes, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("estado", listado)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.rutaimg, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBox("archivo2", "", new { type = "file", accept = "image/*" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-warning" /> |
                    @Html.ActionLink("Retornar", "Pelicula", null, new { @class = "btn btn-info" })
                </div>
            </div>
        </div>
    }
    <div>
        @ViewBag.mensaje
    </div>
</body>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Proyecto_CineALL/Proyecto_CineALL/Views/Peliculas/Pelicula.cshtml
@model IEnumerable<Models.Peliculas>

@{
    ViewBag.Title = "Pelicula";
}
<style>


    body {
        background-image: url('/FOTOS/BLACK1.PNG');
        background-repeat: no-repeat;
        background-size: cover;
    }
</style>
<body>
    <br />
    <br />
    <h2>Pelicula</h2>

    <p>
        @Html.ActionLink("Crear Pelicula", "Create")
    </p>
    <br />
    <table class="table">
        <tr>
            <th>
                CÓDIGO
            </th>
            <th>
                PELICULA
            </th>
            <th>
                TIPO
            </th>
            <th>
                FECHA ESTRENO
            </th>
            <th>
                FECHA FINAL
            </th>
            <th>
                PRECIO
            </th>
            <th>
                ENTRADAS DISPONIBLES
            </th>
            <th>
                ESTADO
            </th>
            <th></th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.codigo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.descripcionTipo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fechaEstreno)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fechaFinal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.precio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.entradasRestantes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.estado)
                </td>
                <td>
                    <img src="@Url.Content(item.rutaimg)" style="width:40px; height:40px" />
                </td>
                <td>
                    @Html.ActionLink("Actualizar", "Edit", new { codigo = item.codigo }, new { @class = "btn btn-warning" }) |
                    @Html.ActionLink("Eliminar", "Delete", new { codigo = item.codigo }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }

    </table>
</body>