Proyecto_CineALL/Proyecto_CineALL/Controllers/ComestiblesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto_CineALL.ServiceReference1;
using System.Data.SqlClient;
using Models;

namespace Proyecto_CineALL.Controllers
{
    public class ComestiblesController : Controller
    {
        Service1Client servicio = new Service1Client();
        public ActionResult Comestible()
        {
            return View(servicio.comestibles());
        }

        public ActionResult Create()
        {
            ViewBag.tipcomestibles = new SelectList(servicio.tipocomestibles(), "id", "descrip");
            ViewBag.proveedor = new SelectList(servicio.proveedor(), "id", "nombre");
            return View(new Comestibles());
        }

        [HttpPost]
        public ActionResult Create(Comestibles reg, HttpPostedFileBase archivo)
        {
            if (archivo == null || archivo.ContentLength <= 0)
            {
                ViewBag.mensaje = "Seleccione una imagen";
                ViewBag.tipcomestibles = new SelectList(servicio.tipocomestibles(), "id", "descrip");
                ViewBag.proveedor = new SelectList(servicio.proveedor(), "id", "nombre");
                return View(reg);
            }
            //si seleccionaste, lo guardamos en la carpeta FOTOS
            string ruta = "~/FOTOS/" + System.IO.Path.GetFileName(archivo.FileName);
            reg.rutaimg = ruta;
            archivo.SaveAs(Server.MapPath(ruta));

            ViewBag.mensaje = servicio.AgregarCome(reg);
            ViewBag.tipcomestibles = new SelectList(servicio.tipocomestibles(), "id", "descrip", reg.id_Tipo);
            ViewBag.proveedor = new SelectList(servicio.proveedor(), "id", "nombre", reg.id_proveedor);
            return View(reg);
        }

        public ActionResult Edit(string cod_Com)
        {
            if (string.IsNullOrEmpty(cod_Com)) return RedirectToAction("Index");
            Comestibles reg = servicio.comestibles().Where(s => s.cod_Com == cod_Com).FirstOrDefault();
            ViewBag.tipcomestibles = new SelectList(servicio.tipocomestibles(), "id", "descrip", reg.id_Tipo);
            ViewBag.proveedor = new SelectList(servicio.proveedor(), "id", "nombre", reg.id_proveedor);
            return View(reg);
        }
        [HttpPost]
        public ActionResult Edit(Comestibles reg, HttpPostedFileBase archivo)
        {
            if (archivo != null)
            {
                //si seleccionaste, lo guardamos en la carpeta FOTOS
                string ruta = "~/FOTOS/" + System.IO.Path.GetFileName(archivo.FileName);
                archivo.SaveAs(Server.MapPath(ruta));
                reg.rutaimg = ruta;
            }

            ViewBag.mensaje = servicio.ActualizarCome(reg);
            ViewBag.tipcomestibles = new SelectList(servicio.tipocomestibles(), "id", "descrip", reg.id_Tipo);
            ViewBag.proveedor = new SelectList(servicio.proveedor(), "id", "nombre", reg.id_proveedor);
            return View(reg);
        }
        public ActionResult Delete(Comestibles reg)
        {
            TempData["mensaje"] = servicio.EliminarCome(reg);

            return RedirectToAction("Comestible");
        }
    }

}

Proyecto_CineALL/Proyecto_CineALL/Views/Comestibles/Comestible.cshtml
@model IEnumerable<Models.Comestibles>

@{
    ViewBag.Title = "Comestible";
}
<style>


    body {
        background-image: url('/FOTOS/BLACK1.PNG');
        background-repeat: no-repeat;
        background-size: cover;
    }
</style>
<body>
    <br />
    <br />
    <h2>Comestible</h2>

    <p>
        @Html.ActionLink("Crear Comestible", "Create", new { @class = "btn btn-primary" })
    </p>
    <br />
    <table class="table">
        <tr>
            <th>
                CÓDIGO
            </th>
            <th>
                DESCRIPCIÓN
            </th>
            <th>
                PRECIO
            </th>
            <th>
                STOCK
            </th>
            <th>
                TIPO
            </th>
            <th>
                PROVEEDOR
            </th>
            <th>
                ESTADO
            </th>
            <th></th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.cod_Com)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.descrip)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.precio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.stock_Actual)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.descripcionTipo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.descripcionProveedor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.estado)
                </td>
                <td>
                    <img src="@Url.Content(item.rutaimg)" style="width:40px; height:40px" />
                </td>
                <td>
                    @Html.ActionLink("Actualizar", "Edit", new { cod_Com = item.cod_Com }, new { @class = "btn btn-warning" }) |
                    @Html.ActionLink("Eliminar", "Delete", new { cod_Com = item.cod_Com }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }

    </table>
</body>

Proyecto_CineALL/Proyecto_CineALL/Views/Comestibles/Create.cshtml
@model Models.Comestibles
@using Models
@{
    ViewBag.Title = "Create";
}
<style>


    body {
        background-image: url('/FOTOS/BLACK2.PNG');
        background-repeat: no-repeat;
        background-size: cover;
    }
</style>
<body>
    <br />
    <h2>Crear</h2>
    @{
        var listado = new List<SelectListItem>() {
         new SelectListItem()
          {
              Text = "Activo",
              Value = "A"

          },
        new SelectListItem()
        {
            Text="Inhabilitado",
            Value="I"

        }
    };
    }

    @using (Html.BeginForm("Create", "Comestibles", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Comestibles</h4>
    <br />
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.descrip, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.descrip, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.descrip, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.stock_Actual, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.stock_Actual, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.stock_Actual, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.id_Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("id_Tipo", ViewBag.tipcomestibles as SelectList)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.id_proveedor, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("id_proveedor", ViewBag.proveedor as SelectList)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("estado", listado)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.rutaimg, htmlAttributes: new { @class = "control-label col-md-2" })

        <div class="col-md-10">
            @Html.TextBox("archivo", "", new { type = "file", accept = "image/*" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-success" /> |
            @Html.ActionLink("Retornar", "Comestible", null, new { @class = "btn btn-info" })
        </div>
    </div>
</div>
    }
    <div>
        @ViewBag.mensaje
    </div>
</body>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Proyecto_CineALL/Proyecto_CineALL/Views/Comestibles/Edit.cshtml
@model Models.Comestibles
@using Models
@{
    ViewBag.Title = "Edit";
}
<style>


    body {
        background-image: url('/FOTOS/BLACK3.PNG');
        background-repeat: no-repeat;
        background-size: cover;
    }
</style>
<body>
    <br />
    <h2>Actualizar</h2>
    @{
        var listado = new List<SelectListItem>() {
         new SelectListItem()
          {
              Text = "Activo",
              Value = "A"

          },
        new SelectListItem()
        {
            Text="Inhabilitado",
            Value="I"

        }
    };
    }

    @using (Html.BeginForm("Edit", "Comestibles", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Comestibles</h4>
    <br />
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.cod_Com, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.cod_Com, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
            @Html.ValidationMessageFor(model => model.cod_Com, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.descrip, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.descrip, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.descrip, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.stock_Actual, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.stock_Actual, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.stock_Actual, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.id_Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("id_Tipo", ViewBag.tipcomestibles as SelectList)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.id_proveedor, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("id_proveedor", ViewBag.proveedor as SelectList)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("estado", listado)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.rutaimg, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBox("archivo", "", new { type = "file", accept = "image/*" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-warning" /> |
            @Html.ActionLink("Retornar", "Comestible", null, new { @class = "btn btn-info" })
        </div>
    </div>
</div>
    }
    <div>
        @ViewBag.mensaje
    </div>
</body>
        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }